# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Copy SSL certificate and key
COPY nginx.crt /home/
COPY nginx.key /home/
COPY PanelPage /usr/share/nginx/PanelPage

# Expose ports for HTTP and HTTPS
EXPOSE 80
EXPOSE 443

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]