version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: minityhyi/mysqldb:2.0
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_USER=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=DBSimpel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./init.sql:/data/application/init.sql

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

